[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
description = ""
version = "0.1.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "src/test/py",
    "src/integration/py"
]